spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel4.cloudtype.app:32727/bucktime
    username: root
    password: password
  config:
    activate:
      on-profile: dev