spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bucktime
    username: root
    password: parksj11
  config:
    activate:
      on-profile: jbjeong
  
  devtools:
    livereload:
      enabled: true