CREATE TABLE user (
user_mail VARCHAR(50) NOT NULL PRIMARY KEY,
user_name VARCHAR(10) NOT NULL,
auth VARCHAR(20) NOT NULL DEFAULT 'USER',
phone_number VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(80) NOT NULL
);

CREATE TABLE cafe (
cafe_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cafe_description TEXT,
cafe_address VARCHAR(50) NOT NULL,
cafe_name VARCHAR(30) NOT NULL,
owner_mail VARCHAR(50) NOT NULL,
open_time CHAR(4) NOT NULL,
close_time CHAR(4) NOT NULL,
call_number VARCHAR(20) NOT NULL,
FOREIGN KEY (owner_mail) REFERENCES user(user_mail) ON DELETE CASCADE
);

CREATE TABLE desk (
desk_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
desk_name VARCHAR(10) NOT NULL,
cafe_idx INT NOT NULL,
price VARCHAR(10) NOT NULL,
capacity SMALLINT NOT NULL DEFAULT 4,
FOREIGN KEY (cafe_idx) REFERENCES cafe(cafe_idx) ON DELETE CASCADE
);

CREATE TABLE menu (
menu_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
menu_name VARCHAR(20) NOT NULL,
menu_description TEXT NOT NULL,
menu_price INT NOT NULL,
cafe_idx INT NOT NULL,
FOREIGN KEY (cafe_idx) REFERENCES cafe(cafe_idx) ON DELETE CASCADE
);

CREATE TABLE notice (
notice_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
notice_title VARCHAR(50) NOT NULL,
notice_content VARCHAR(1000) NOT NULL,
notice_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `order` (
order_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
menu_idx INT NOT NULL,
user_mail VARCHAR(50) NOT NULL,
FOREIGN KEY (menu_idx) REFERENCES menu(menu_idx) ON DELETE CASCADE,
FOREIGN KEY (user_mail) REFERENCES user(user_mail) ON DELETE CASCADE,
completion BOOLEAN NOT NULL DEFAULT '0'
);

CREATE TABLE reservation(
rez_idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
start_time TIMESTAMP NOT NULL,
finish_time TIMESTAMP NOT NULL,
user_mail VARCHAR(50) NOT NULL,
desk_idx INT NOT NULL,
FOREIGN KEY (user_mail) REFERENCES user(user_mail) ON DELETE CASCADE,
FOREIGN KEY (desk_idx) REFERENCES desk(desk_idx) ON DELETE CASCADE,
used BOOLEAN NOT NULL DEFAULT '0'
);